---
namespace: community
name: mysql
version: 5.0.2
readme: README.md
authors:
  - Ansible community
description: MySQL and MariaDB collection for Ansible
license_file: COPYING
dependencies:
  ansible.mysql: '>=4.2.1'
tags:
  - database
  - mysql
  - mariadb
repository: https://github.com/ansible-collections/ansible.mysql
documentation: https://github.com/ansible-collections/ansible.mysql
homepage: https://github.com/ansible-collections/ansible.mysql
issues: https://github.com/ansible-collections/ansible.mysql/issues
