---
name: Docker Image CI my80-py38-mysqlclient201

on:
  push:
    paths:
      - 'test-containers/my80-py38-mysqlclient201/**'
      - '.github/workflows/docker-image-my80-py38-mysqlclient201.yml'

jobs:

  call-workflow-passing-data:
    uses: build-docker-image.yml@main
    secrets: inherit
    with:
      registry: ghcr.io
      image_name: test-container-my80-py38-mysqlclient201
      context: test-containers/my80-py38-mysqlclient201
