---
name: Docker Image CI mariadb106-py310-mysqlclient211

on:
  push:
    paths:
      - 'test-containers/mariadb106-py310-mysqlclient211/**'
      - '.github/workflows/docker-image-mariadb106-py310-mysqlclient211.yml'

jobs:

  call-workflow-passing-data:
    uses: build-docker-image.yml@main
    secrets: inherit
    with:
      registry: ghcr.io
      image_name: test-container-mariadb106-py310-mysqlclient211
      context: test-containers/mariadb106-py310-mysqlclient211
